facts = [
    "Did you know that we bin around 50 million tonnes of electrical waste globally every year.",
    "Did you know that we throw away 7.2 million tonnes of food every year, and more than half of it’s perfectly edible.",
    "Did you know that between 20% and 40% of fruit and vegetables are rejected by supermarkets before they even hit the shelves, just because they don’t adhere to their cosmetic standard.",
    "Did you know that the amount of trash generated by the UK could fill Britain’s largest lake, Lake Windermere, in just 8 months.",
    "Did you know that we used to get through 500 million plastic bags every week in the UK? The usage has dropped by a staggering 85% since the introduction of the 5p bag. A win for Mother Earth.",
    "Did you know that at Christmas, as much as 83 square kilometres of wrapping paper will end up in UK bins when it could have been recycled instead.",
    "Did you know that the number of disposable nappies each baby gets through weighs the same as a family car!",
    "Did you know that humans now buy a million plastic bottles a minute. By 2050, the ocean will contain more plastic by weight than fish.",
    "Did you know that it’s not just what goes in the bin that counts as waste – water can be wasted, too. A single leaky tap in your house can waste as much as 5,000 litres of water a year."
]

questions = [
    "On average, each person in the UK throws away their own body weight in rubbish every seven weeks.",
    "The average UKfamily throws away 6 trees worth of paper in their household bin a year.",
    "Plastic bags should go into the recycling bin.",
    "The current president of the united states is making all his effort to protect the environment"
]

answers = [
    "yes",
    "yes",
    "no",
    "no"
]